import type { ProjectScan } from './scan/types.js';
import { renderTree } from './scan/tree.js';

export function buildComprehensiveReadme(scan: ProjectScan): string {
  const lines: string[] = [
    `# ${scan.name}`,
    '',
    scan.description || `${scan.type} project.`,
    '',
    '> Onboarding README generated by **README Doctor**. Review auto-detected sections before commit.',
    '',
    '## Quick start',
    '',
    '```bash',
    'npm install',
    'cp .env.example .env   # if present',
    'npm start',
    '```',
    '',
  ];

  if (scan.apis.some((e) => e.path.includes('/health'))) {
    const port = scan.envVars.find((v) => v.name === 'PORT')?.example?.replace(/['"]/g, '') || '3001';
    const health = scan.apis.find((e) => e.path.includes('/health'));
    lines.push(`Health: \`http://localhost:${port}${health?.path ?? '/api/health'}\``, '');
  }

  if (scan.git.isRepo) {
    lines.push('## Source control', '');
    if (scan.git.remoteUrl) lines.push(`- **Remote:** ${scan.git.remoteUrl}`);
    if (scan.git.branch) lines.push(`- **Branch:** \`${scan.git.branch}\``);
    if (scan.hasCi) lines.push('- **CI:** GitHub Actions (`.github/workflows/`)');
    lines.push('');
  }

  lines.push('## Project structure', '');
  if (Object.keys(scan.topLevelNotes).length > 0) {
    lines.push('| Path | Purpose |', '| --- | --- |');
    for (const [dir, note] of Object.entries(scan.topLevelNotes).sort()) {
      lines.push(`| \`${dir}/\` | ${note} |`);
    }
    lines.push('');
  }

  lines.push('### Directory tree', '', renderTree(scan.tree), '');

  if (scan.hasDataDir) {
    lines.push(
      '### Data layout',
      '',
      'Local files under `data/` (no database in v1). Example retrospective folder:',
      '',
      '```text',
      'data/retrospectives/{retroId}/',
      '├── retro.json',
      '├── feedback/',
      '├── analysis.json',
      '├── actions.json',
      '├── report.md',
      '└── audit.jsonl',
      '```',
      ''
    );
  }

  if (scan.hasConfigDir) {
    lines.push('### Configuration', '', '- `config/` — runtime JSON (e.g. guardrails, teams)', '');
  }

  if (scan.apis.length > 0) {
    const port = scan.envVars.find((v) => v.name === 'PORT')?.example?.replace(/['"]/g, '') || '3001';
    const healthPath = scan.apis.find((e) => e.path.includes('/health'))?.path ?? `${scan.apiMountPrefix}/health`;

    lines.push(
      '## API',
      '',
      `${scan.apis.length} HTTP endpoints (base path \`${scan.apiMountPrefix}\`). Detected from route files.`,
      '',
      '| Method | Path | Source |',
      '| --- | --- | --- |'
    );
    for (const ep of scan.apis) {
      lines.push(`| ${ep.method} | \`${ep.path}\` | \`${ep.sourceFile}\` |`);
    }
    lines.push(
      '',
      '### Health check',
      '',
      '```bash',
      `curl http://localhost:${port}${healthPath}`,
      '```',
      ''
    );
  }

  if (scan.apis.some((e) => e.path.includes('/analysis/import'))) {
    lines.push(
      '## Analysis model',
      '',
      '| Source | How |',
      '| --- | --- |',
      '| **Cursor agent** (primary) | `/analyze-retro` → `POST .../analysis/import` |',
      '| **Baseline** (tests only) | `POST .../analysis/generate/baseline` |',
      '',
      'No external LLM API keys in this service. AI analysis is performed by the Cursor agent in the parent orchestration repo.',
      ''
    );
  }

  if (scan.hasDataDir && scan.name.includes('retro')) {
    lines.push(
      '## Data storage',
      '',
      'JSON and Markdown under `data/retrospectives/{retroId}/`. Status lifecycle: `draft` → `open` → `closed` → `archived`.',
      ''
    );
  }

  if (scan.cursor.length > 0) {
    lines.push(
      '## Cursor / agentic AI',
      '',
      'Cursor rules and workflow assets detected in this repo:',
      ''
    );

    const groups: Record<string, typeof scan.cursor> = {
      rule: [],
      agent: [],
      skill: [],
      command: [],
      hook: [],
    };
    for (const asset of scan.cursor) {
      groups[asset.kind].push(asset);
    }

    const titles: Record<string, string> = {
      rule: 'Rules',
      agent: 'Sub-agents',
      skill: 'Skills',
      command: 'Commands',
      hook: 'Hooks',
    };

    for (const [kind, title] of Object.entries(titles)) {
      const items = groups[kind];
      if (!items.length) continue;
      lines.push(`### ${title}`, '');
      for (const item of items) {
        const desc = item.description ? ` — ${item.description}` : '';
        lines.push(`- **${item.name}** (\`${item.path}\`)${desc}`);
      }
      lines.push('');
    }

    lines.push(
      'If this repo is part of a monorepo, the root `.cursor/` folder may hold workflow commands (`/analyze-retro`, `/generate-report`, etc.), skills, and sub-agents. Check the parent `AGENTS.md` and `docs/cursor-test-workflow.md`.',
      ''
    );
  }

  if (scan.agentsMdPath) {
    lines.push(`Agent boundaries: [\`${scan.agentsMdPath}\`](${scan.agentsMdPath}).`, '');
  }

  if (scan.envVars.length > 0) {
    lines.push(
      '## Environment',
      '',
      'Copy `.env.example` to `.env` and set:',
      '',
      '| Variable | Example | Description |',
      '| --- | --- | --- |'
    );
    for (const v of scan.envVars) {
      lines.push(`| \`${v.name}\` | ${v.example ? `\`${v.example}\`` : '—'} | ${v.description} |`);
    }
    lines.push('');
  }

  if (Object.keys(scan.allScripts).length > 0) {
    lines.push('## NPM scripts', '', '| Script | Command |', '| --- | --- |');
    for (const [name, cmd] of Object.entries(scan.allScripts)) {
      lines.push(`| \`${name}\` | \`${cmd}\` |`);
    }
    lines.push('');
  }

  if (scan.hasTests) {
    lines.push(
      '## Testing',
      '',
      '```bash',
      'npm test',
      '```',
      '',
      scan.hasCi ? 'CI runs tests on push/PR via GitHub Actions.' : '',
      ''
    );
  }

  return lines.filter((l) => l !== undefined).join('\n').replace(/\n{3,}/g, '\n\n');
}
